Add vote listing for users
Typiqally/quote-wall pull request #8
Opened 2023-12-07 08:18 UTC by ScriptDeBurger

2023-12-07 08:58 UTC, Typiqally commented
Fix merge conflicts please

2023-12-07 10:39 UTC, ScriptDeBurger commented
I solved the conflicts, can you review the code?

2023-12-07 12:18 UTC, Typiqally requested changes

2023-12-07 12:18 UTC, Typiqally commented on src/routes/api/quotes/+server.ts
> +
Remove this

2023-12-07 12:18 UTC, Typiqally commented on src/routes/api/quotes/votes/+server.ts
> +    const getVotes = await db.vote.findMany({
votes

2024-01-18 09:28 UTC, Typiqally approved these changes

2024-01-18 09:28 UTC, merged